added pagination and responsivness
jordus100/Bot-Wars-front pull request #62
Opened 2024-05-30 11:22 UTC by StanislawMalinski

2024-05-30 20:15 UTC, jordus100 requested changes
Spoko, ale do doszlifowania, bo leaderboard wypełnia tylko pół ekranu:
![image](https://github.com/jordus100/Bot-Wars-front/assets/92371238/e89e8edd-968a-4819-9b5e-9455fc5005f5)
Poza tym skoro już jesteśmy przy paginatorze to fajnie by naprawić wyskakujące cyferki w miarę możliwości.

2024-05-30 20:19 UTC, jordus100 commented
a i po kliknięciu w leaderboarda wywala error

2024-05-30 21:04 UTC, StanislawMalinski commented
dodałem fix'a

2024-06-01 14:05 UTC, jordus100 requested changes
paginacja wygląda teraz super, ale leaderboard nadal jest zbyt mały bez powodu

2024-06-08 13:04 UTC, jordus100 approved these changes
kozak, nawet jest responsywne

2024-06-08 13:04 UTC, merged